str1 = input('input string 1: ')
str2 = input('input string 2: ')
str3 = input('input string 3: ')
str4 = input('input string 4: ')
f = open('strings.txt', 'w')
f.write(str1 + '\n')
f.write(str2 + '\n')
f.close()
f = open('strings.txt', 'a')
f.write(str3 + '\n')
f.write(str4 + '\n')
f.close()